version: 0.2

phases:
  pre_build:
    commands:
  build:
    commands:
      - echo Build started on `date`
      # path of pom file
      - cd ./cicdtest
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - ls
artifacts:
  files:
      - '*/*.jar'
  base-directory: cicdtest
  name: submodel-$(date +%Y-%m-%d)