version: 0.2

env:
  variables:
    S3_BUCKET: 'cicd-test-submodle'
    S3_PREFIX: 'submodels/'
phases:
  build:
    commands:
      - echo Build started on `date`
      # path of pom file
      - cd ./cicdtest
      - mvn install
artifacts:
  files:
      - '*/*.jar'
  base-directory: '/'
  name: 'submodel-1'
  discard-paths: yes


post_build:
  commands:
    - echo Build completed on `date`