on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Main Workflow
      uses: actions/github-script@v5
      with:
        script: |
          try {
            await github.rest.actions.createWorkflowDispatch({
              owner: 'botian123123',
              repo: 'testShell',
              workflow_id: 'build.yml',
              ref: 'main',
            });
            console.log('Build workflow triggered successfully.');
          } catch (error) {
            console.error('Error:', error);
            throw error;
          }