on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Main Workflow
      uses: actions/github-script@v5
      with:
        script: |
          const octokit = new Octokit({
            auth: process.env.secrets.GH_PAT
          })

          await octokit.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
            owner: 'OWNER',
            repo: 'REPO',
            workflow_id: 'WORKFLOW_ID',
            ref: 'topic-branch',
            headers: {
              'X-GitHub-Api-Version': '2022-11-28'
            }
          })